### ISSUE TITLE
Add project types, 'internal' and 'external', to first step of project workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science#835]
These concept labels would need to be added to the RDM

**Comment by annabelleee** [comment]
@chiatt What node is this associated with?

**Comment by aarongundel** [comment]
Feedback from @njkim : 
ok. It looks like the project type(?) was meant to be added to the workflow.
And Activity Type of Project was added (which looks like listing the techniques actually) but I guess the Scale of project meant to be added instead (which includes initiative,
project, research task)

So it sounds like we need to modify the node in use here to be the scale of project node instead of the project type node, right @annabelleee ?  We're uncertain how internal/external will fall into this.

**Comment by annabelleee** [comment]
@aarongundel Yes on modifying the node to be scale of project node. Regarding internal/external, I will find out next week asking others in the modeling group.

**Comment by aarongundel** [comment]
Sounds.  @annabelleee I'm noting that this ticket is labeled with "Proposal" - I'm going to make a separate ticket for modifying the node to be scale of project.   That sounds like a bug.  When you're ready for this to be actionable, just unassign yourself and remove the propsal tag and we'll take it from there.

**Comment by aarongundel** [comment]
![Screen Shot 2022-09-19 at 3 55 55 PM](https://user-images.githubusercontent.com/124614/191126718-eacc8e0e-f71c-45d0-b2c9-f14100cec477.png)
FYI @annabelleee this is done, looks like there's a typo in the "project" value for this node, though.  Seems like that's another RDM update that will need to be done.

**Comment by jacobtylerwalls** [comment]
Spelling of "projets" was addressed in archesproject/arches#9849
